### ISSUE TITLE
Oh Noes errors

### ISSUE THREAD

**Issue by KeiroD** [blesta/module-tastyinterworx#1]
Edit: Just gonna throw a bunch of Oh Noes! errors in here.

Only a couple things are working in the Tasty InterWorx module: Change Password and Install Web Applications... or so it seems.

Selecting Account Usage in the client's dashboard results in the following error:

```
Oh noes!

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://:/soap?wsdl' : failed to load external entity "https://:/soap?wsdl" on line 18 in /home/example/web/example.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php 

Printing Stack Trace:
#0 /home/example/web/example.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(18): SoapClient->SoapClient('https://:/soap?...')
#1 /home/example/web/example.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(459): tastywiApi->doTheConnect('/nodeworx/sitew...', 'querySiteworxAc...', Array)
#2 /home/example/web/example.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(2185): tastywiApi->getSiteworxAccountInfo(NULL)
#3 /home/example/web/example.com/public_html/billing/app/controllers/client_services.php(106): Tastyinterworxmodule->accountusage(Object(stdClass), Object(stdClass), Array, Array, Array)
#4 /home/example/web/example.com/public_html/billing/lib/dispatcher.php(111): ClientServices->manage()
#5 /home/example/web/example.com/public_html/billing/index.php(21): Dispatcher::dispatch('/billing/client...')
#6 {main}
```

Selecting e-mail accounts results in the following: 

```
Oh noes!

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://:/soap?wsdl' : failed to load external entity "https://:/soap?wsdl" on line 31 in /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php 

Printing Stack Trace:
#0 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(31): SoapClient->SoapClient('https://:/soap?...')
#1 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(212): tastywiApi->doTheConnectSiteWorx('/siteworx/email...', NULL, NULL, NULL, 'listEmailBoxes', Array)
#2 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(2105): tastywiApi->listEmailBoxes(NULL, NULL, NULL)
#3 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(240): Tastyinterworxmodule->emailmain(Object(stdClass), Object(stdClass), Array, Array, Array)
#4 /home/eidolon/web/eidolonhost.com/public_html/billing/app/controllers/client_services.php(106): Tastyinterworxmodule->email(Object(stdClass), Object(stdClass), Array, Array, Array)
#5 /home/eidolon/web/eidolonhost.com/public_html/billing/lib/dispatcher.php(111): ClientServices->manage()
#6 /home/eidolon/web/eidolonhost.com/public_html/billing/index.php(21): Dispatcher::dispatch('/billing/client...')
#7 {main}
```

Selecting e-mail aliases results in:

```
Oh noes!

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://:/soap?wsdl' : failed to load external entity "https://:/soap?wsdl" on line 31 in /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php 

Printing Stack Trace:
#0 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(31): SoapClient->SoapClient('https://:/soap?...')
#1 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(257): tastywiApi->doTheConnectSiteWorx('/siteworx/email...', NULL, NULL, NULL, 'listEmailAliase...', Array)
#2 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(1894): tastywiApi->listEmailAlias(NULL, NULL, NULL)
#3 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(226): Tastyinterworxmodule->emailaliasmain(Object(stdClass), Object(stdClass), Array, Array, Array)
#4 /home/eidolon/web/eidolonhost.com/public_html/billing/app/controllers/client_services.php(106): Tastyinterworxmodule->emailalias(Object(stdClass), Object(stdClass), Array, Array, Array)
#5 /home/eidolon/web/eidolonhost.com/public_html/billing/lib/dispatcher.php(111): ClientServices->manage()
#6 /home/eidolon/web/eidolonhost.com/public_html/billing/index.php(21): Dispatcher::dispatch('/billing/client...')
#7 {main}
```

Selecting FTP accounts results in:

```
Oh noes!

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://:/soap?wsdl' : failed to load external entity "https://:/soap?wsdl" on line 31 in /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php 

Printing Stack Trace:
#0 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(31): SoapClient->SoapClient('https://:/soap?...')
#1 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(78): tastywiApi->doTheConnectSiteWorx('/siteworx/ftp', NULL, NULL, NULL, 'listFtpAccounts', Array)
#2 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(1774): tastywiApi->listFtpAccounts(NULL, NULL, NULL)
#3 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(214): Tastyinterworxmodule->ftpaccountsmain(Object(stdClass), Object(stdClass), Array, Array, Array)
#4 /home/eidolon/web/eidolonhost.com/public_html/billing/app/controllers/client_services.php(106): Tastyinterworxmodule->ftpaccounts(Object(stdClass), Object(stdClass), Array, Array, Array)
#5 /home/eidolon/web/eidolonhost.com/public_html/billing/lib/dispatcher.php(111): ClientServices->manage()
#6 /home/eidolon/web/eidolonhost.com/public_html/billing/index.php(21): Dispatcher::dispatch('/billing/client...')
#7 {main}
```

Selecting Sub domains results in:

```
Oh noes!

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://:/soap?wsdl' : failed to load external entity "https://:/soap?wsdl" on line 31 in /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php 

Printing Stack Trace:
#0 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(31): SoapClient->SoapClient('https://:/soap?...')
#1 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(316): tastywiApi->doTheConnectSiteWorx('/siteworx/domai...', NULL, NULL, NULL, 'listSubdomains', Array)
#2 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(1642): tastywiApi->listSubDomains(NULL, NULL, NULL)
#3 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(202): Tastyinterworxmodule->subdomainsmain(Object(stdClass), Object(stdClass), Array, Array, Array)
#4 /home/eidolon/web/eidolonhost.com/public_html/billing/app/controllers/client_services.php(106): Tastyinterworxmodule->subdomains(Object(stdClass), Object(stdClass), Array, Array, Array)
#5 /home/eidolon/web/eidolonhost.com/public_html/billing/lib/dispatcher.php(111): ClientServices->manage()
#6 /home/eidolon/web/eidolonhost.com/public_html/billing/index.php(21): Dispatcher::dispatch('/billing/client...')
#7 {main}
```

Selecting Secondary domains results in:

```
Oh noes!

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://:/soap?wsdl' : failed to load external entity "https://:/soap?wsdl" on line 31 in /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php 

Printing Stack Trace:
#0 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(31): SoapClient->SoapClient('https://:/soap?...')
#1 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(287): tastywiApi->doTheConnectSiteWorx('/siteworx/domai...', NULL, NULL, NULL, 'listSecondaryDo...', Array)
#2 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(1525): tastywiApi->listAddonDomains(NULL, NULL, NULL)
#3 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(190): Tastyinterworxmodule->secondarydomainsmain(Object(stdClass), Object(stdClass), Array, Array, Array)
#4 /home/eidolon/web/eidolonhost.com/public_html/billing/app/controllers/client_services.php(106): Tastyinterworxmodule->secondarydomains(Object(stdClass), Object(stdClass), Array, Array, Array)
#5 /home/eidolon/web/eidolonhost.com/public_html/billing/lib/dispatcher.php(111): ClientServices->manage()
#6 /home/eidolon/web/eidolonhost.com/public_html/billing/index.php(21): Dispatcher::dispatch('/billing/client...')
#7 {main}
```

Selecting pointer domains results in:

```
Oh noes!

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://:/soap?wsdl' : failed to load external entity "https://:/soap?wsdl" on line 31 in /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php 

Printing Stack Trace:
#0 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(31): SoapClient->SoapClient('https://:/soap?...')
#1 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(345): tastywiApi->doTheConnectSiteWorx('/siteworx/domai...', NULL, NULL, NULL, 'listPointerDoma...', Array)
#2 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(1414): tastywiApi->listDomainsRedirects(NULL, NULL, NULL)
#3 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(178): Tastyinterworxmodule->pointerdomainsmain(Object(stdClass), Object(stdClass), Array, Array, Array)
#4 /home/eidolon/web/eidolonhost.com/public_html/billing/app/controllers/client_services.php(106): Tastyinterworxmodule->pointerdomains(Object(stdClass), Object(stdClass), Array, Array, Array)
#5 /home/eidolon/web/eidolonhost.com/public_html/billing/lib/dispatcher.php(111): ClientServices->manage()
#6 /home/eidolon/web/eidolonhost.com/public_html/billing/index.php(21): Dispatcher::dispatch('/billing/client...')
#7 {main}
```

Selecting databases results in:

```
Oh noes!

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://:/soap?wsdl' : failed to load external entity "https://:/soap?wsdl" on line 31 in /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php 

Printing Stack Trace:
#0 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(31): SoapClient->SoapClient('https://:/soap?...')
#1 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(376): tastywiApi->doTheConnectSiteWorx('/siteworx/mysql...', NULL, NULL, NULL, 'listMysqlDataba...', Array)
#2 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(602): tastywiApi->listDatabases(NULL, NULL, NULL)
#3 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(128): Tastyinterworxmodule->databasesmain(Object(stdClass), Object(stdClass), Array, Array, Array)
#4 /home/eidolon/web/eidolonhost.com/public_html/billing/app/controllers/client_services.php(106): Tastyinterworxmodule->databases(Object(stdClass), Object(stdClass), Array, Array, Array)
#5 /home/eidolon/web/eidolonhost.com/public_html/billing/lib/dispatcher.php(111): ClientServices->manage()
#6 /home/eidolon/web/eidolonhost.com/public_html/billing/index.php(21): Dispatcher::dispatch('/billing/client...')
#7 {main}
```

Selecting cronjobs results in:

```
Oh noes!

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://:/soap?wsdl' : failed to load external entity "https://:/soap?wsdl" on line 31 in /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php 

Printing Stack Trace:
#0 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(31): SoapClient->SoapClient('https://:/soap?...')
#1 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(178): tastywiApi->doTheConnectSiteWorx('/siteworx/cron', NULL, NULL, NULL, 'list', Array)
#2 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(1291): tastywiApi->listCron(NULL, NULL, NULL)
#3 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(166): Tastyinterworxmodule->cronjobsmain(Object(stdClass), Object(stdClass), Array, Array, Array)
#4 /home/eidolon/web/eidolonhost.com/public_html/billing/app/controllers/client_services.php(106): Tastyinterworxmodule->cronjobs(Object(stdClass), Object(stdClass), Array, Array, Array)
#5 /home/eidolon/web/eidolonhost.com/public_html/billing/lib/dispatcher.php(111): ClientServices->manage()
#6 /home/eidolon/web/eidolonhost.com/public_html/billing/index.php(21): Dispatcher::dispatch('/billing/client...')
#7 {main}
```

Selecting Backups results in:

```
Oh noes!

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://:/soap?wsdl' : failed to load external entity "https://:/soap?wsdl" on line 31 in /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php 

Printing Stack Trace:
#0 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(31): SoapClient->SoapClient('https://:/soap?...')
#1 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(110): tastywiApi->doTheConnectSiteWorx('/siteworx/backu...', NULL, NULL, NULL, 'listAllBackups', Array)
#2 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(1120): tastywiApi->listBackups(NULL, NULL, NULL)
#3 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(154): Tastyinterworxmodule->backupsmain(Object(stdClass), Object(stdClass), Array, Array, Array)
#4 /home/eidolon/web/eidolonhost.com/public_html/billing/app/controllers/client_services.php(106): Tastyinterworxmodule->backups(Object(stdClass), Object(stdClass), Array, Array, Array)
#5 /home/eidolon/web/eidolonhost.com/public_html/billing/lib/dispatcher.php(111): ClientServices->manage()
#6 /home/eidolon/web/eidolonhost.com/public_html/billing/index.php(21): Dispatcher::dispatch('/billing/client...')
#7 {main}
```

Selecting Install Application brings me to a new install application screen. Clicking Install New App works, as does the pop-up. List backups in the same screen also works.

**Comment by clphillips** [comment]
It's missing the hostname. I wonder if you have it configured correctly?

**Comment by KeiroD** [comment]
@clphillips 

Yep. See: 
![tasty](https://cloud.githubusercontent.com/assets/3938118/10473121/1f85624e-71ed-11e5-9acc-8d20bdbf9cdf.png)

Edit: Also, just to be sure, I checked to ensure php-soap was installed, it is. Server outputs `php-soap.x86_64 0:5.3.3-46.el6_6` as the answer when I queried it to see if it was installed.

**Comment by KeiroD** [comment]
@clphillips I also tried `https}://{$this->hostname}:{$this->port}/soap?wsdl");`

It immediately threw this error:

```
Oh noes!

SOAP-ERROR: Parsing WSDL: Couldn't load from '://:/soap?wsdl' : failed to load external entity "://:/soap?wsdl" on line 18 in /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php 

Printing Stack Trace:
#0 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(18): SoapClient->SoapClient('://:/soap?wsdl')
#1 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(459): tastywiApi->doTheConnect('/nodeworx/sitew...', 'querySiteworxAc...', Array)
#2 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(2185): tastywiApi->getSiteworxAccountInfo(NULL)
#3 /home/eidolon/web/eidolonhost.com/public_html/billing/app/controllers/client_services.php(113): Tastyinterworxmodule->accountusage(Object(stdClass), Object(stdClass), Array, Array, Array)
#4 /home/eidolon/web/eidolonhost.com/public_html/billing/lib/dispatcher.php(111): ClientServices->manage()
#5 /home/eidolon/web/eidolonhost.com/public_html/billing/index.php(21): Dispatcher::dispatch('/billing/client...')
#6 {main}
```

I also tried `https}://daedalus.eidolonhost.com:2443/soap?wsdl");`

No joy, either. However... I wonder... let me try something.

**Comment by KeiroD** [comment]
Well, that's interesting.

Trying `https}://{daedalus.eidolonhost.com:2443}/soap?wsdl");`

results in the following error:

```
Oh noes!

SOAP-ERROR: Parsing WSDL: Couldn't load from '://{daedalus.eidolonhost.com:2443}/soap?wsdl' : failed to load external entity "://{daedalus.eidolonhost.com:2443}/soap?wsdl" on line 18 in /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php 

Printing Stack Trace:
#0 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(18): SoapClient->SoapClient('://{daedalus.ei...')
#1 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(459): tastywiApi->doTheConnect('/nodeworx/sitew...', 'querySiteworxAc...', Array)
#2 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(2185): tastywiApi->getSiteworxAccountInfo(NULL)
#3 /home/eidolon/web/eidolonhost.com/public_html/billing/app/controllers/client_services.php(113): Tastyinterworxmodule->accountusage(Object(stdClass), Object(stdClass), Array, Array, Array)
#4 /home/eidolon/web/eidolonhost.com/public_html/billing/lib/dispatcher.php(111): ClientServices->manage()
#5 /home/eidolon/web/eidolonhost.com/public_html/billing/index.php(21): Dispatcher::dispatch('/billing/client...')
#6 {main}
```

**Comment by clphillips** [comment]
Not sure why, but it's not getting the hostname. I haven't even tried this, and only had a cursory glance at the code. I'd need to dig into it to figure out the issue.

**Comment by clphillips** [comment]
> Trying https}://{daedalus.eidolonhost.com:2443}/soap?wsdl");

That is interesting...

**Comment by KeiroD** [comment]
Trying `https}//{daedalus.eidolonhost.com:2443}/soap?wsdl");`

Results in:

```
Oh noes!

SOAP-ERROR: Parsing WSDL: Couldn't load from '//{daedalus.eidolonhost.com:2443}/soap?wsdl' : failed to load external entity "/{daedalus.eidolonhost.com:2443}/soap?wsdl" on line 18 in /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php 

Printing Stack Trace:
#0 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(18): SoapClient->SoapClient('//{daedalus.eid...')
#1 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/apis/bakediw_api.php(459): tastywiApi->doTheConnect('/nodeworx/sitew...', 'querySiteworxAc...', Array)
#2 /home/eidolon/web/eidolonhost.com/public_html/billing/components/modules/tastyinterworxmodule/tastyinterworxmodule.php(2185): tastywiApi->getSiteworxAccountInfo(NULL)
#3 /home/eidolon/web/eidolonhost.com/public_html/billing/app/controllers/client_services.php(113): Tastyinterworxmodule->accountusage(Object(stdClass), Object(stdClass), Array, Array, Array)
#4 /home/eidolon/web/eidolonhost.com/public_html/billing/lib/dispatcher.php(111): ClientServices->manage()
#5 /home/eidolon/web/eidolonhost.com/public_html/billing/index.php(21): Dispatcher::dispatch('/billing/client...')
#6 {main}
```

It is interesting. The format of the SOAP link is essentially correct, as seen [here](http://docs.interworx.com/interworx/api/api.full.php)
